name: publish-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      build_command: make kernel && make data && jupyter-book build . ; jupyter-book build .
      environment_name: eo-datascience-cookbook

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
